import { StyleSheet, Platform } from 'react-native';
import { COLORS } from '../../constants/colors';
import { SPACING } from '../../constants/spacing';
import { FONTS } from '../../constants/fonts';

export const styles = StyleSheet.create({
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: COLORS.white },
  safeArea: { flex: 1, backgroundColor: COLORS.textMedium },
  flex1: { flex: 1, backgroundColor: COLORS.offWhite },

  // Modal styles strictly merged
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
  modalContent: { backgroundColor: COLORS.white, borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: SPACING.l, paddingBottom: SPACING.xxxl },
  modalTitle: { fontSize: 14, fontFamily: FONTS.bold, color: COLORS.textDark, lineHeight: 20, marginBottom: SPACING.l },
  variantRow: { flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: COLORS.borderDark, borderRadius: 12, padding: SPACING.s, marginBottom: SPACING.m },
  variantImageContainer: { width: 44, height: 44, borderRadius: 6, backgroundColor: COLORS.inputBg, justifyContent: 'center', alignItems: 'center', marginRight: SPACING.m, position: 'relative' },
  variantImage: { width: 32, height: 32 },
  variantBadge: { position: 'absolute', top: -6, right: -6, backgroundColor: COLORS.orange, width: 16, height: 16, borderRadius: 8, justifyContent: 'center', alignItems: 'center' },
  variantBadgeText: { color: COLORS.white, fontSize: 9, fontFamily: FONTS.bold },
  variantInfo: { flex: 1, flexDirection: 'row', alignItems: 'center' },
  variantWeight: { fontSize: 12, color: COLORS.textMedium, marginRight: SPACING.m, fontFamily: FONTS.medium },
  variantPriceBox: { flexDirection: 'row', alignItems: 'baseline' },
  variantPrice: { fontSize: 13, fontFamily: FONTS.bold, color: COLORS.textDark, marginRight: 4 },
  variantOrigPrice: { fontSize: 11, color: COLORS.textLight, textDecorationLine: 'line-through' },
  modalAddBtn: { backgroundColor: COLORS.primary, paddingHorizontal: 24, paddingVertical: 8, borderRadius: 6, minWidth: 70, alignItems: 'center' },
  modalAddText: { color: COLORS.white, fontSize: 12, fontFamily: FONTS.bold },
  modalQtySelector: { flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: COLORS.primary, borderRadius: 6, height: 32, backgroundColor: COLORS.white },
  modalQtyBtn: { paddingHorizontal: 8, height: '100%', justifyContent: 'center' },
  modalQtyText: { color: COLORS.primary, fontSize: 12, fontFamily: FONTS.bold, minWidth: 16, textAlign: 'center' },
  confirmBtn: { backgroundColor: COLORS.confirmGreen, paddingVertical: 14, borderRadius: 8, alignItems: 'center', marginTop: SPACING.s },
  confirmBtnText: { color: COLORS.white, fontSize: 14, fontFamily: FONTS.bold },

  header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: SPACING.m, height: 60, backgroundColor: COLORS.white },
  iconBtn: { padding: 4, width: 40 },
  headerTitle: { flex: 1, fontSize: 16, fontFamily: FONTS.bold, color: COLORS.textDark, textAlign: 'center' },

  savingsBannerTop: { backgroundColor: COLORS.tealLight, paddingVertical: 10, alignItems: 'center', marginHorizontal: SPACING.m, borderRadius: 8, marginVertical: SPACING.m },
  savingsBannerTopText: { color: COLORS.teal, fontSize: 12, fontFamily: FONTS.bold },

  yellowWarningBanner: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.yellowLight, paddingHorizontal: 12, paddingVertical: 12, marginHorizontal: SPACING.m, borderRadius: 8, borderWidth: 1, borderColor: COLORS.yellowBorder, marginBottom: SPACING.m },
  warningIconCirc: { width: 16, height: 16, borderRadius: 8, backgroundColor: COLORS.yellow, justifyContent: 'center', alignItems: 'center', marginRight: 12 },
  yellowWarningText: { flex: 1, color: COLORS.yellowDark, fontSize: 11, fontFamily: FONTS.medium, lineHeight: 16 },

  cartItemsBlock: { backgroundColor: COLORS.white, paddingHorizontal: SPACING.m, paddingBottom: SPACING.m },
  cartItemRow: { flexDirection: 'row', alignItems: 'flex-start', marginVertical: 12 },
  cartItemImageContainer: { width: 44, height: 44, backgroundColor: COLORS.iconBg, borderRadius: 8, justifyContent: 'center', alignItems: 'center', marginRight: 12 },
  cartItemImage: { width: 32, height: 32 },
  cartItemInfo: { flex: 1, marginRight: 12 },
  cartItemTitle: { fontSize: 12, fontFamily: FONTS.medium, color: COLORS.textDark, lineHeight: 18, marginBottom: 4 },
  cartItemWeight: { fontSize: 11, color: COLORS.textLight },
  cartItemRight: { alignItems: 'flex-end', width: 70 },
  cartItemPrices: { flexDirection: 'row', alignItems: 'baseline', marginTop: 8 },
  cartItemPrice: { fontSize: 13, fontFamily: FONTS.bold, color: COLORS.textDark, marginRight: 4 },
  cartItemOrigPrice: { fontSize: 10, color: COLORS.textLight, textDecorationLine: 'line-through' },

  compactQtySelector: { flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: COLORS.primary, borderRadius: 6, height: 30, backgroundColor: COLORS.white, width: '100%' },
  qtyBtn: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  qtyText: { color: COLORS.primary, fontSize: 12, fontFamily: FONTS.bold },

  // Out of stock
  outOfStockContainer: { backgroundColor: COLORS.white, borderWidth: 1, borderColor: COLORS.redBorder, borderRadius: 12, overflow: 'hidden', marginBottom: 20 },
  outOfStockHeader: { backgroundColor: COLORS.redLight, paddingVertical: 8, alignItems: 'center' },
  outOfStockHeaderText: { color: COLORS.red, fontSize: 12, fontFamily: FONTS.bold },
  outOfStockRow: { flexDirection: 'row', alignItems: 'center', padding: SPACING.m, paddingBottom: SPACING.s },
  deleteBtn: { borderWidth: 1, borderColor: COLORS.primary, borderRadius: 6, paddingHorizontal: 16, height: 32, justifyContent: 'center', alignItems: 'center' },
  deleteBtnText: { color: COLORS.primary, fontSize: 11, fontFamily: FONTS.bold },
  similarItemsContainer: { paddingHorizontal: SPACING.m, paddingBottom: SPACING.m },
  similarItemsTitle: { fontSize: 13, fontFamily: FONTS.bold, color: COLORS.textDark, marginBottom: SPACING.m, marginTop: SPACING.s },

  brandText: { fontSize: 10, color: COLORS.textMuted, marginBottom: 2 },
  suggestedCard: { width: 140, backgroundColor: COLORS.white, marginRight: 12, position: 'relative' },
  discountTagSmall: { position: 'absolute', top: 0, left: 0, backgroundColor: COLORS.tealDark, paddingHorizontal: 6, paddingVertical: 4, borderBottomRightRadius: 8, borderTopLeftRadius: 8, zIndex: 10, alignItems: 'center' },
  discountText: { color: COLORS.white, fontSize: 10, fontFamily: FONTS.bold, lineHeight: 12 },
  discountTextSmall: { color: COLORS.white, fontSize: 8, fontFamily: FONTS.bold, lineHeight: 10 },
  suggestedImgBox: { backgroundColor: COLORS.inputBg, borderRadius: 12, borderWidth: 1, borderColor: COLORS.offWhite, justifyContent: 'center', alignItems: 'center', padding: 16, marginBottom: 8 },
  suggestedImage: { width: 60, height: 60 },
  suggestedTitle: { fontSize: 12, fontFamily: FONTS.medium, color: COLORS.textDark, height: 34, lineHeight: 16, marginBottom: 4 },
  suggestedWeight: { fontSize: 10, color: COLORS.textMuted, marginBottom: 8 },
  suggestedActionRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'baseline' },
  suggestedPriceBox: { flexDirection: 'row', alignItems: 'baseline' },
  suggestedPrice: { fontSize: 13, fontFamily: FONTS.bold, color: COLORS.textDark, marginRight: 4 },
  suggestedOrigPrice: { fontSize: 10, color: COLORS.textLight, textDecorationLine: 'line-through' },
  greenSolidBtn: { backgroundColor: COLORS.primary, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 8, paddingVertical: 6, borderRadius: 6 },
  greenSolidText: { color: COLORS.white, fontSize: 10, fontFamily: FONTS.bold },

  divider: { height: 1, backgroundColor: COLORS.dividerLight, width: '100%' },
  sectionPadding: { padding: SPACING.m },
  sectionTitle: { fontSize: 15, fontFamily: FONTS.bold, color: COLORS.textDark, marginBottom: 16 },

  couponsOuterBox: { marginHorizontal: SPACING.m, marginBottom: SPACING.m, padding: SPACING.s, backgroundColor: COLORS.pillBgBlue, borderWidth: 1, borderColor: COLORS.pillBgCyan, borderRadius: 12 },
  couponsHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 8, marginBottom: 8 },
  iconCircleBlueMini: { width: 14, height: 14, borderRadius: 7, backgroundColor: COLORS.primary, justifyContent: 'center', alignItems: 'center', marginRight: 6 },
  sectionTitleOptions: { fontSize: 13, fontFamily: FONTS.bold, color: COLORS.primary },

  couponCard: { width: 130, backgroundColor: COLORS.white, borderRadius: 12, padding: 12, marginRight: 12, alignItems: 'center', borderWidth: 1, borderColor: COLORS.borderLight, elevation: 1, shadowColor: COLORS.black, shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05, shadowRadius: 2 },
  couponCardApplied: { borderColor: COLORS.orangeBorder, backgroundColor: COLORS.orangeLight },
  couponTopCirc: { width: 44, height: 44, borderRadius: 22, backgroundColor: COLORS.teal, justifyContent: 'center', alignItems: 'center', marginBottom: 16 },
  couponTopCircText: { color: COLORS.white, fontSize: 12, fontFamily: FONTS.bold },
  couponTopCircSub: { color: COLORS.white, fontSize: 9, fontFamily: FONTS.bold },
  couponDashedLine: { height: 1, width: '100%', borderColor: '#DDD', borderWidth: 1, borderStyle: 'dashed', position: 'absolute', top: 56 },
  couponWarningText: { fontSize: 10, color: COLORS.red, textAlign: 'center', marginBottom: 8, lineHeight: 14 },
  couponDescText: { fontSize: 10, color: COLORS.textMuted, textAlign: 'center', marginBottom: 8, lineHeight: 14 },
  couponCodeBox: { borderStyle: 'dashed', borderWidth: 1, borderColor: '#CCC', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 4, marginBottom: 12 },
  couponCodeText: { fontSize: 12, fontFamily: FONTS.bold, color: COLORS.textDark },
  couponApplyBtn: { color: COLORS.orange, fontSize: 11, fontFamily: FONTS.bold },
  couponApplyBtnApplied: { color: COLORS.white, backgroundColor: COLORS.orange, paddingHorizontal: 12, paddingVertical: 4, borderRadius: 4, overflow: 'hidden' },

  couponSavedMsg: { backgroundColor: COLORS.pillBgTeal, marginHorizontal: SPACING.m, paddingVertical: 10, borderRadius: 8, alignItems: 'center', marginTop: 12, marginBottom: 16 },
  couponSavedText: { color: COLORS.teal, fontSize: 12 },
  couponSavedBold: { fontFamily: FONTS.bold },
  viewMoreRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingBottom: 8 },
  viewMoreText: { fontSize: 13, color: COLORS.textSecondary, marginRight: 4, fontFamily: FONTS.medium },

  cashbackBox: { marginHorizontal: SPACING.m, paddingVertical: SPACING.m, borderBottomWidth: 1, borderBottomColor: COLORS.dividerLight },
  cashbackRow: { flexDirection: 'row', alignItems: 'flex-start', backgroundColor: COLORS.background, padding: 16, borderRadius: 8, borderWidth: 1, borderColor: COLORS.dividerLight },
  iconCircleBlueHero: { width: 40, height: 40, borderRadius: 20, backgroundColor: COLORS.pillBgCyan, justifyContent: 'center', alignItems: 'center' },
  cashbackTitle: { fontSize: 13, fontFamily: FONTS.bold, color: COLORS.textDark, marginBottom: 4 },
  cashbackDesc: { fontSize: 11, color: COLORS.textMuted },

  sectionTitleSmall: { fontSize: 13, fontFamily: FONTS.bold, color: COLORS.textDark, marginBottom: 12 },
  instructionsScroll: { flexDirection: 'row', marginBottom: SPACING.m },
  pill: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.white, borderWidth: 1, borderColor: COLORS.border, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 16, marginRight: 12 },
  pillText: { fontSize: 11, color: COLORS.textDark, marginLeft: 6 },
  instructionInput: { backgroundColor: COLORS.background, borderWidth: 1, borderColor: COLORS.borderLight, borderRadius: 8, paddingHorizontal: 16, height: 44, fontSize: 13, color: COLORS.textDark },

  billDetailsContainer: { backgroundColor: COLORS.white, margin: SPACING.m, borderRadius: 16, padding: SPACING.m, borderWidth: 1, borderColor: COLORS.dividerLight },
  billRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  billRowLeft: { flexDirection: 'row', alignItems: 'center' },
  billLabel: { fontSize: 12, color: COLORS.textMedium },
  savedOrangeTag: { backgroundColor: COLORS.orangeLight, paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4, marginLeft: 8 },
  savedOrangeText: { color: COLORS.orange, fontSize: 9, fontFamily: FONTS.bold },
  billValue: { fontSize: 13, color: COLORS.textDark, fontFamily: FONTS.medium },
  billRowLeftCol: { flex: 1 },
  deliverySublabel: { fontSize: 10, color: COLORS.orange, marginTop: 2 },
  freeDeliveryBox: { flexDirection: 'row', alignItems: 'center' },
  strikethroughPrice: { color: COLORS.textLight, textDecorationLine: 'line-through', fontSize: 12, marginRight: 6 },
  freeText: { color: COLORS.primary, fontSize: 12, fontFamily: FONTS.bold },
  dashedDivider: { height: 1, width: '100%', borderColor: '#DDD', borderWidth: 1, borderStyle: 'dashed' },
  totalLabel: { fontSize: 14, fontFamily: FONTS.bold, color: COLORS.textDark },
  totalValue: { fontSize: 15, fontFamily: FONTS.bold, color: COLORS.textDark },

  savingsBannerBottom: { backgroundColor: COLORS.tealLight, marginTop: 16, paddingVertical: 12, alignItems: 'center', borderRadius: 8, borderStyle: 'dashed', borderWidth: 1, borderColor: COLORS.tealLight },
  savingsBannerBottomText: { color: COLORS.teal, fontSize: 12, fontFamily: FONTS.bold },

  cancellationBox: { marginHorizontal: SPACING.m, backgroundColor: COLORS.offWhite, padding: SPACING.m, borderRadius: 8, borderWidth: 1, borderColor: COLORS.dividerLight },
  cancelTitle: { fontSize: 13, fontFamily: FONTS.bold, color: COLORS.textDark, marginBottom: 6 },
  cancelText: { fontSize: 11, color: COLORS.textMuted, lineHeight: 16 },

  stickyBottom: { backgroundColor: COLORS.white, borderTopWidth: 1, borderTopColor: COLORS.borderLight, elevation: 8, shadowColor: COLORS.black, shadowOffset: { width: 0, height: -2 }, shadowOpacity: 0.05, shadowRadius: 4, paddingBottom: Platform.OS === 'ios' ? 24 : 16 },
  addressRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: SPACING.m, paddingTop: SPACING.m },
  addressLeft: { flexDirection: 'row', alignItems: 'center' },
  deliverToText: { fontSize: 13, color: COLORS.textDark, marginLeft: 8 },
  homeBold: { fontFamily: FONTS.bold },
  changeText: { color: COLORS.primary, fontSize: 13, fontFamily: FONTS.bold },
  addressSubText: { fontSize: 11, color: COLORS.textMuted, paddingHorizontal: SPACING.m, paddingLeft: 38, marginTop: 4, marginBottom: SPACING.s },
  bottomBarRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: SPACING.m, marginTop: 4 },
  totalBox: {},
  toPayLabel: { fontSize: 11, color: COLORS.textMuted, marginBottom: 2 },
  finalTotal: { fontSize: 18, fontFamily: FONTS.bold, color: COLORS.textDark },
  proceedBtn: { backgroundColor: COLORS.primary, paddingHorizontal: 32, paddingVertical: 12, borderRadius: 8 },
  proceedBtnLarge: { backgroundColor: COLORS.primary, paddingHorizontal: 24, paddingVertical: 12, borderRadius: 8 },
  proceedText: { color: COLORS.white, fontSize: 15, fontFamily: FONTS.bold },

  // New Utility Styles to remove inline ones
  chevronMini: { marginLeft: 2 },
  warningExclamation: { color: COLORS.white, fontSize: 10, fontWeight: 'bold' },
  outOfStockOpacity: { opacity: 0.5 },
  negativeMarginM: { marginHorizontal: -SPACING.m },
  horizontalListPadding: { paddingHorizontal: SPACING.m },
  emptyCartContainer: { padding: 40, alignItems: 'center' },
  emptyCartText: { fontSize: 16, color: COLORS.textLight, fontFamily: FONTS.medium },
  whiteMiniText: { color: COLORS.white, fontSize: 10 },
  xIconMini: { marginLeft: 4 },
  couponListPadding: { paddingHorizontal: SPACING.m, paddingBottom: 16 },
  cashbackImg: { width: 20, height: 20, borderRadius: 10 },
  cashbackInfo: { marginLeft: 12, flex: 1 },
  dashedDividerSpacer: { height: 1, width: '100%', borderColor: '#DDD', borderWidth: 1, borderStyle: 'dashed', marginVertical: SPACING.m },
  mapPinBubble: { backgroundColor: COLORS.teal, width: 24, height: 24, borderRadius: 12, justifyContent: 'center', alignItems: 'center', marginRight: 8 },
  disabledOpacity: { opacity: 0.3 },
  spacer120: { height: 120 },
});
